/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2018-09-20 02:44:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sys.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<link href=\"../../css/css/bootstrap.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link href=\"//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\t\tbackface-visibility:hidden;\r\n");
      out.write("\t\t\t\tbackground:#fff;\r\n");
      out.write("\t\t\t\tcolor: #41B733;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t/********* nav *******\r\n");
      out.write("            ***/\r\n");
      out.write("\t\t\t.fixed{\r\n");
      out.write("\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\tbackground: #3e3e3e;\r\n");
      out.write("\t\t\t\tz-index: 100;\r\n");
      out.write("\t\t\t\tleft: 0px;\r\n");
      out.write("\t\t\t\ttop: 40px;\r\n");
      out.write("\t\t\t\tpadding: 0 0px;\r\n");
      out.write("\t\t\t\tborder-radius:  0px;\r\n");
      out.write("\t\t\t\tborder: none;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#userMessage > img{\r\n");
      out.write("\t\t\t\tdisplay: block;\r\n");
      out.write("\t\t\t\twidth: 80px;\r\n");
      out.write("\t\t\t\theight: 80px;\r\n");
      out.write("\t\t\t\tborder:3px solid #31B0D;\r\n");
      out.write("\t\t\t\tborder-radius: 50px;\r\n");
      out.write("\t\t\t\tmargin: 15px auto;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#userMessage > div{\r\n");
      out.write("\t\t\t\twidth: 100px;\r\n");
      out.write("\t\t\t\theight: 36px;\r\n");
      out.write("\t\t\t\tborder:none;\r\n");
      out.write("\t\t\t\tborder-radius: 0px;\r\n");
      out.write("\t\t\t\tmargin: 0 auto 10px auto;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t\tline-height: 30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t/*** userMessage 的兄弟div\"**/\r\n");
      out.write("\t\t\t#userMessage + div{\r\n");
      out.write("\t\t\t\tmargin: 100px auto;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] {\r\n");
      out.write("\t\t\t\tdisplay:none;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] + label {\r\n");
      out.write("\t\t\t\tposition: fixed;\r\n");
      out.write("\t\t\t\tleft:0px;\r\n");
      out.write("\t\t\t\ttop:0px;\r\n");
      out.write("\t\t\t\tz-index: 100;\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\twidth:40px;\r\n");
      out.write("\t\t\t\theight:40px;\r\n");
      out.write("\t\t\t\tbackground:#3e3e3e;\r\n");
      out.write("\t\t\t\tcursor:pointer;\r\n");
      out.write("\t\t\t\tfont-size:30px;\r\n");
      out.write("\t\t\t\tcolor:#fff;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] + label span {\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\tleft:8px;\r\n");
      out.write("\t\t\t\ttransition:.2s;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"]:checked + label span {\r\n");
      out.write("\t\t\t\ttransform:rotate(180deg);\r\n");
      out.write("\t\t\t\tfont-size:34px;\r\n");
      out.write("\t\t\t\ttop:-2px;\r\n");
      out.write("\t\t\t\tleft:9px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tnav a {\r\n");
      out.write("\t\t\t\tdisplay:block;\r\n");
      out.write("\t\t\t\theight:40px;\r\n");
      out.write("\t\t\t\tline-height:40px;\r\n");
      out.write("\t\t\t\tbackground:#3e3e3e;\r\n");
      out.write("\t\t\t\twidth:100px;\r\n");
      out.write("\t\t\t\tpadding-left:10px;\r\n");
      out.write("\t\t\t\ttext-decoration:none;\r\n");
      out.write("\t\t\t\tcolor:white;\r\n");
      out.write("\t\t\t\tbox-shadow:5px 0 0 #000;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(1) { box-shadow:5px 0 0 #3498db; transition-delay:.05s; text-decoration: none}/*规定nav子元素的颜色过渡时间*/\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(2) { box-shadow:5px 0 0 #2ecc71; transition-delay:.10s; text-decoration: none}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(3) { box-shadow:5px 0 0 #e67e22; transition-delay:.15s; text-decoration: none}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(4) { box-shadow:5px 0 0 #c0392b; transition-delay:.20s; text-decoration: none}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(5) { box-shadow:5px 0 0 #2c3e50; transition-delay:.25s; text-decoration: none}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:nth-child(6) { box-shadow:5px 0 0 #9999FF; transition-delay:.30s; text-decoration: none}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"]:checked ~ nav{\r\n");
      out.write("\t\t\t\tmargin-left:0px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav {\r\n");
      out.write("\t\t\t\tmargin-left:-110px;\r\n");
      out.write("\t\t\t\ttransition:.6s margin;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"]:checked ~ nav a {\r\n");
      out.write("\t\t\t\tmargin-left:0px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"]:checked ~ nav a:hover {\r\n");
      out.write("\t\t\t\twidth:100px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a {\r\n");
      out.write("\t\t\t\tmargin-left:-110px;\r\n");
      out.write("\t\t\t\ttransition:.6s margin;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tinput[id=\"daohang\"] ~ nav a:hover {\r\n");
      out.write("\t\t\t\tbackground:#999;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t/***\r\n");
      out.write("            ********* nav *******/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t/******** 顶部退出栏 ****\r\n");
      out.write("            ***/\r\n");
      out.write("\t\t\t#top > div{\r\n");
      out.write("\t\t\t\tfloat: right;\r\n");
      out.write("\t\t\t\tposition: relative;\r\n");
      out.write("\t\t\t\twidth: 70px;\r\n");
      out.write("\t\t\t\theight: 35px;\r\n");
      out.write("\t\t\t\tright: 16px;\r\n");
      out.write("\t\t\t\ttop: 8px;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tline-height: 35px;\r\n");
      out.write("\t\t\t\tbackground: #fff;\r\n");
      out.write("\t\t\t\ttext-align: center;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t#top >div:hover{\r\n");
      out.write("\t\t\t\tbackground: gray;\r\n");
      out.write("\t\t\t\tcolor: white\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/***\r\n");
      out.write("            ******** 顶部退出栏 ****/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t/******* 内容栏  ************\r\n");
      out.write("            ***/\r\n");
      out.write("\t\t\t/**** 内容栏外边距  ****/\r\n");
      out.write("\t\t\t#centern{\r\n");
      out.write("\t\t\t\twidth: inherit;\r\n");
      out.write("\t\t\t\tpadding-top: 15px;\r\n");
      out.write("\t\t\t\tpadding-bottom: 15px;\r\n");
      out.write("\t\t\t\tmargin-bottom: 15px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t/***内部窗体**/\r\n");
      out.write("\t\t\t#myFrame{\r\n");
      out.write("\t\t\t\twidth: 100%;\r\n");
      out.write("\t\t\t\tborder-radius: 5px;\r\n");
      out.write("\t\t\t\tborder-width: 0;\r\n");
      out.write("\t\t\t\tbackground: gray;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t/***\r\n");
      out.write("            ******* 内容栏  ************/\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--导航栏-->\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"daohang\" checked/>\r\n");
      out.write("\t\t\t<label for=\"daohang\"><span><i class=\"fa fa-arrow-left\"></i></span></label>\r\n");
      out.write("\t\t<nav class=\"fixed\">\t\t\t\t\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<div id=\"userMessage\">\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<img style=\"\" src=\"sys/main/touxiang.jpg\" width=\"100px\"/>\r\n");
      out.write("\t\t\t\t\t<div>欢迎您</div>\r\n");
      out.write("\t\t\t\t\t<div id = \"userName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></lable>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a herf=\"#\"></a>\r\n");
      out.write("\t\t\t\t<a target=\"nameIframe\" href=\"MusicServlet?flag=queryByPage\" onclick=\"\">音乐库</a>\r\n");
      out.write("\t\t\t\t<a target=\"nameIframe\" href=\"sys/user/userEdit.jsp\" onclick=\"\">用户信息修改</a>\r\n");
      out.write("\t\t\t\t<a target=\"nameIframe\" href=\"UserServlet?flag=queryType\">我的歌曲</a>\r\n");
      out.write("\t\t\t\t<a href=\"LoginoutServlet\" title=\"退出系统\" class=\"dl-log-quit\">退出x</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--内容栏-->\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div id=\"centern\" class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<iframe id=\"myFrame\" style=\"z-index: 0;\" name=\"nameIframe\" href=\"\">\r\n");
      out.write("\t\t\t\t\t</iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t/**\r\n");
      out.write("\t * globle vary\r\n");
      out.write("\t */\r\n");
      out.write("\tvar buttonchosed;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction initialize(){\r\n");
      out.write("\t\tvar myFrame = document.getElementById(\"myFrame\");\r\n");
      out.write("\t\tmyFrame.onload = alterIframe;\r\n");
      out.write("\t\tmyFrame.src = \"MusicServlet?flag=queryByPage\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeButtonLook(o){\r\n");
      out.write("\t\tif(buttonchosed){\r\n");
      out.write("\t\t\tbuttonchosed.style.background = \"#fff\";\r\n");
      out.write("\t\t\tbuttonchosed.style.color = \"#41B733\";\r\n");
      out.write("\t\t\tbuttonchosed.onmouseover = function(){\r\n");
      out.write("\t\t\t\tbuttonchosed.style.background = \"gray\";\r\n");
      out.write("\t\t\t\tbuttonchosed.style.color = \"#fff\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\to.style.background = \"gray\";\r\n");
      out.write("\t\to.style.color = \"#fff\";\r\n");
      out.write("\t\tbuttonchosed = o;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loginQuit(){\r\n");
      out.write("\t\tvar user = document.getElementById(\"userMessage\").getElementsByTagName(\"div\")[0];\r\n");
      out.write("\t\tvar xhr = new XMLHttpRequest();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txhr.open(\"POST\", \"url\", true);\r\n");
      out.write("\t\txhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\txhr.send(\"account=\" + user.innerText);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.location.href = \"url\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction alterIframe(){\r\n");
      out.write("\t\tvar myFrame = document.getElementById(\"myFrame\");\r\n");
      out.write("\t\tvar doc = myFrame.contentWindow.document;\r\n");
      out.write("\t\tvar height = doc.documentElement.scrollHeight;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdoc.parentDocument = reflushUserMessage;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(height != myFrame.height){\r\n");
      out.write("\t\t\tmyFrame.height = height + 10;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction iframeScaleChange(){\r\n");
      out.write("\t\tvar cendiv = document.getElementById(\"centern\").getElementsByTagName(\"div\");\r\n");
      out.write("\t\tvar fisrtdiv = cendiv[0];\r\n");
      out.write("\t\tvar lastdiv = cendiv[1];\r\n");
      out.write("\t\tvar bros = document.getElementById(\"myFrame\").parentNode.getElementsByTagName(\"div\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(bros);\r\n");
      out.write("\t\tif(bros[1].style.display == \"block\"){\r\n");
      out.write("\t\t\tbros[1].style.display = \"none\";\r\n");
      out.write("\t\t\tbros[0].style.display = \"block\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfisrtdiv.style.display = \"block\";\r\n");
      out.write("\t\t\tfisrtdiv.classList.add(\"col-lg-2\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlastdiv.classList.remove(\"col-lg-12\");\r\n");
      out.write("\t\t\tlastdiv.classList.add(\"col-lg-10\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tbros[0].style.display = \"none\";\r\n");
      out.write("\t\t\tbros[1].style.display = \"block\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfisrtdiv.style.display = \"none\";\r\n");
      out.write("\t\t\tfisrtdiv.classList.remove(\"col-lg-2\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlastdiv.classList.remove(\"col-lg-10\");\r\n");
      out.write("\t\t\tlastdiv.classList.add(\"col-lg-12\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction reflushUserMessage(mes){\r\n");
      out.write("\r\n");
      out.write("\t\t//console.log(mes + \"cccccc\");\r\n");
      out.write("\t\tvar data = document.getElementById(\"userName\");\r\n");
      out.write("\t\tmes = new DOMParser().parseFromString(mes,\"text/xml\");\r\n");
      out.write("\t\tconsole.log(\"fff\");\t\t\r\n");
      out.write("\t\tconsole.log(mes);\r\n");
      out.write("\t\r\n");
      out.write("\t\tmes = mes.getElementsByTagName(\"name\");//getElementsByName(\"name\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"sss\");\t\t\r\n");
      out.write("\t\tconsole.log(mes);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(data.innerText);\r\n");
      out.write("\t\tdata.innerText = mes[0].textContent;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//data[1].innerText = mes.getElementsByName(\"nickname\").textContent;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tinitialize();\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
